### ISSUE TITLE
Atlassian Scraper Handler

### ISSUE THREAD

**Issue by debayangg** [Pavel401/Jobs-Scraper#12]
I have fixed the Atlassian scraper handler and updated the model and code and it is working but I got the URL for fetching the job listings from atlassians career portal's network requests, its not from any official atlassian api list, so idk about any rate limits or anything.

The URL I'm using is: `"https://www.atlassian.com/endpoint/careers/listings"`

Should I create a PR for it?

**Comment by Pavel401** [comment]
@debayangg  yeah sure .

**Comment by debayangg** [comment]
@Pavel401  Can you merge the unit tests PR then, it will make it easier to push a merge-able branch with the atlassian scraper.

**Comment by Pavel401** [comment]
> @Pavel401 Can you merge the unit tests PR then, it will make it easier to push a merge-able branch with the atlassian scraper.

Done

**Comment by debayangg** [comment]
Sent a [PR](https://github.com/Pavel401/Jobs-Scraper/pull/13) that fixes this issue.
