### ISSUE TITLE
Improve Frontend UI

### ISSUE THREAD

**Issue by sambitsingha** [Pavel401/Jobs-Scraper#14]
- The frontend of the website needs much improvement , in terms of font , background color or image and also improvement in terms of UX also. 
- I would like to work on this issue for KWoC.
<br>

**Comment by sambitsingha** [comment]
@Pavel401 Please tell me where to add the CSS file . I am not familiar with Go bascially

**Comment by Pavel401** [comment]
Place it inside the 'static' folder. You need to locally run the Golang API to fetch jobs during development.

**Comment by Pavel401** [comment]
@sambitsingha are you still working on this ?

**Comment by sambitsingha** [comment]
Yes yes @Pavel401 I was abit busy actually. If I can't complete it , I will let you know. For the time being , I am still in

**Comment by sambitsingha** [comment]
@Pavel401 Can you guide me on how to run the website. I am having problem in establishing the environment

**Comment by Pavel401** [comment]
clone the repo 
cd repo
go mod tidy
go run main.go

**Comment by sambitsingha** [comment]
I installed Go , having problem in Gin

**Comment by Pavel401** [comment]
What's the issue you are facing ?

**Comment by sambitsingha** [comment]
I am facing issue in installing Gin , the terminal shows -- ``"go" can't be recognized``  whenever I run those commands. 
Tell me the detailed process on installing Go and Gin and how to setup the environment before I give styling

**Comment by Pavel401** [comment]
https://go.dev/doc/install
Follow this to install Golang 

https://bobbyhadz.com/blog/go-is-not-recognized-as-internal-or-external-command#:~:text=The%20error%20%22'go'%20is,your%20system's%20PATH%20environment%20variable.

**Comment by sambitsingha** [comment]
I am sorry , but I have tried my best to make this work. But I am really having problem with Go and can't proceed to the CSS. Sorry for the inconvenience @Pavel401
