### ISSUE TITLE
Improve the Job card design on the frontend 

### ISSUE THREAD

**Issue by Pavel401** [Pavel401/Jobs-Scraper#17]
Areas for Improvement:
User Interface (UI) Enhancements:

Identify and implement improvements to the overall UI for a more intuitive and visually pleasing experience.
Responsive Design:

Ensure the front end is responsive across various devices and screen sizes.
Accessibility:

Evaluate and enhance accessibility features to make our project more inclusive.
Performance Optimization:

Implement optimizations to improve the frontend's loading speed and responsiveness.
Interactive Elements:

Add or improve interactive elements to make the user interaction more engaging.
Contribution Guidelines:
Fork the Repository:

Fork the repository to your own GitHub account.
Create a Branch:

Create a new branch for your front-end improvements to keep things isolated.
Code Quality:

Follow best practices for frontend development.
Ensure your code is well-documented.
Testing:

Test your changes across different browsers to ensure compatibility.
Submission Process:

Submit a pull request with a clear title and description of your frontend improvements.
How to Contribute:
Check for Existing Issues:

Before starting, check if there are existing issues or pull requests related to frontend improvements.
Discuss Ideas:

Feel free to discuss your ideas with the community and gather feedback before implementation.
Iterative Development:

Consider an iterative development approach, seeking feedback and making adjustments as needed.
Collaboration:

Collaborate with other contributors if there are multiple individuals interested in improving the frontend.
Additional Information:
If you have any questions or need assistance, don't hesitate to reach out.
Your contributions are highly valued, and we look forward to seeing the project's frontend flourish with your improvements!

**Comment by GitWiz01** [comment]
Hello @Pavel401 
I'm a UI Designer
I have worked with Grabetern and Synclify(web extension) before which u can check out on my profile
I have seen your website and it is quite cool I feel I can enhance User interaction and experience with my expertise, and I can lay the wireframe for the improvements on Figma.

Please assign me this under Iwoc24

**Comment by Pavel401** [comment]
@GitWiz01 

Hello! Glad to see your interest in improving the website's UI. Your experience with Grabetern and Synclify is impressive, and I'm excited about the potential enhancements you can bring.
We can discuss the details and collaborate further on our Discord channel. Looking forward to working together to enhance the user interaction and experience. Thanks for stepping up!

**Comment by hemant933** [comment]
can u assign it to me too
