### ISSUE TITLE
Sticky Navbar

### ISSUE THREAD

**Issue by AbhineshJha** [Pavel401/Jobs-Scraper#39]
### Describe your improvement idea or feature request

Wanna fix the navbar to sticky at the top .!

### How would you like to see it implemented?

1.sticky nabvar

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

**Comment by AbhineshJha** [comment]
i HAVE raised the pr , please add the label also. ! @Pavel401

**Comment by Pavel401** [comment]
@all-contributors
please add @AbhineshJha  for code

**Comment by AbhineshJha** [comment]
also add the label here for points @Pavel401

**Comment by Pavel401** [comment]
@AbhineshJha  done

**Comment by AbhineshJha** [comment]
Thank you 😊 @Pavel401
