### ISSUE TITLE
[Feature]: Add the github action workflow for greeting contributors

### ISSUE THREAD

**Issue by praptisharma28** [Pavel401/Jobs-Scraper#43]
### Describe your improvement idea or feature request

The current project lacks an automated action to greet contributors. GitHub Actions can significantly enhance project automation. I propose adding a GitHub Action workflow to greet new pull request (PR) and issue creators, fostering a welcoming environment.

### How would you like to see it implemented?

Implement a GitHub Action workflow that triggers on new PRs and issues. The workflow should include a greeting message to acknowledge and appreciate the contributors for their efforts.

### How can we contact you (optional)

@praptisharma282003@gmail.com

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

**Comment by praptisharma28** [comment]
Hey @Pavel401 add the medium difficult level here too, its not showing on my dashboard @Pavel401 bcz of that.
Also if you can remerge it, it will be better. But let me check if it shows to my dashboard after you add the medium badge. Thanks

**Comment by Pavel401** [comment]
@praptisharma28 I reopened the issue and you can create a fresh PR.

**Comment by praptisharma28** [comment]
https://github.com/Pavel401/Jobs-Scraper/pull/46 here @Pavel401 and thanks tbh. Please add the tags in PR too.

**Comment by praptisharma28** [comment]
Also I opened this same issue in JobScraper- Mobile App. You can assign me there too. @Pavel401
