### ISSUE TITLE
Bug: Correction in Greetings Github Workflow

### ISSUE THREAD

**Issue by praptisharma28** [Pavel401/Jobs-Scraper#49]
### Describe your issue

There is an error in the if condition of greeting github action, remove the if condition so that the test wont fail.

### Steps to reproduce

change the greetings.yml file

### What was the expected result?

Github action running properly

### Put here any screenshots or videos (optional)

![image](https://github.com/Pavel401/Jobs-Scraper/assets/123169861/cbe4f2ce-b1b8-4250-a731-11f5cc925e13)
This needs to be fixed.

### How can we contact you (optional)

@praptisharma282003@gmail.com

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

**Comment by praptisharma28** [comment]
@Pavel401 assign me here

**Comment by Pavel401** [comment]
Please share the demo video or screenshot of the workflow result in your PR.
