### ISSUE TITLE
Bug: jobs div overflow 

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [Pavel401/Jobs-Scraper#52]
### Describe your issue

when you scroll down and then hover over the job post you will notice it overflowing.

![image](https://github.com/Pavel401/Jobs-Scraper/assets/69814563/3e86421b-a73c-4229-bf91-fc07f55888ab)

### Steps to reproduce

1. Open site
2. scroll down a little bit
3. hover on the job post div

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

**Comment by Pavel401** [comment]
<img width="1470" alt="Screenshot 2024-01-26 at 12 41 08 AM" src="https://github.com/Pavel401/Jobs-Scraper/assets/47685150/10742d11-e373-480e-83a7-205221a8f428">
Hey @BamaCharanChhandogi, there's one more issue in the Job card related to the company image; it's set to Boxfit.fit. That's causing image overflow. Can you fix that so the image is visible?

**Comment by BamaCharanChhandogi** [comment]
It's very wired showing different font styles on different browsers.
like in my Chrome:

![image](https://github.com/Pavel401/Jobs-Scraper/assets/69814563/4b76b8c2-65c2-49a3-93c5-6c66c102368e)

**Edge:**

![image](https://github.com/Pavel401/Jobs-Scraper/assets/69814563/1364f4a8-784a-40da-b02d-7bd6470a7c4b)

**Comment by Pavel401** [comment]
@BamaCharanChhandogi, apparently, it's an automated feature in some browsers that resizes text under certain conditions.

Do you want to take your time and fix that issue too? I can change the label to "Hard".

**Comment by Pavel401** [comment]
<img width="821" alt="Screenshot 2024-01-26 at 1 08 52 AM" src="https://github.com/Pavel401/Jobs-Scraper/assets/47685150/fd682b54-2d58-4846-bf70-a2846ffad0cb">
Job card similar to this will look better

**Comment by BamaCharanChhandogi** [comment]
the first issue I have resolved. Do you want this issue will be resolved on the same issue/PR

**Comment by Pavel401** [comment]
@BamaCharanChhandogi  send  another PR

**Comment by BamaCharanChhandogi** [comment]
okay! I am creating another issue/PR related to this problem.

**Comment by BamaCharanChhandogi** [comment]
#53
