### ISSUE TITLE
Overflow issue on Hiver Job card

### ISSUE THREAD

**Issue by Pavel401** [Pavel401/Jobs-Scraper#57]
### Describe your issue

The image URL is invalid, causing overflow issues. To resolve this problem, you need to change the image parameter to the correct one. The file is located at: https://github.com/Pavel401/Jobs-Scraper/blob/main/services/hiverScrapper.go

### Steps to reproduce

Click on the search bar 
enter hiver and see the issue 

### What was the expected result?

It should be visible clearly.

### Put here any screenshots or videos (optional)

<img width="1470" alt="Screenshot 2024-01-28 at 2 53 42 PM" src="https://github.com/Pavel401/Jobs-Scraper/assets/47685150/3cf6d999-edbc-4aa1-a4bd-ac9805a92b35">

### How can we contact you (optional)

NA

### Would you like to work on this issue?

None

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

**Comment by Pavel401** [comment]
@BamaCharanChhandogi @hemant933, do either of you want to work on this? A quick fix is needed.

**Comment by BamaCharanChhandogi** [comment]
Yeah! I will work.

**Comment by BamaCharanChhandogi** [comment]
I am facing some issues.
Why can I not see a 'hiver' company listing in my local area? 
that's why I can not understand whether my approach to solving this problem is right or wrong.
second I have followed these steps to solve this problem.

- add `Image URL` in `hiverScraper.go` files

![image](https://github.com/Pavel401/Jobs-Scraper/assets/69814563/decb91cc-6fe1-4120-8321-d819e469a1ac)

- add the `ImageUrl` field in the `hiver. go` files 

![image](https://github.com/Pavel401/Jobs-Scraper/assets/69814563/74556395-db03-4871-b7e7-48dc9d250a01)

**Comment by Pavel401** [comment]
> I am facing some issues. Why can I not see a `hiver` company listing in my local area? that's why I can not understand whether my approach to solving this problem is right or wrong. second I have followed these steps to solve this problem.
> 
> * add `Image URL` in `hiverScraper.go` files
> 
> ![image](https://private-user-images.githubusercontent.com/69814563/300256829-decb91cc-6fe1-4120-8321-d819e469a1ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDA2NDgsIm5iZiI6MTcwNjQ0MDM0OCwicGF0aCI6Ii82OTgxNDU2My8zMDAyNTY4MjktZGVjYjkxY2MtNmZlMS00MTIwLTgzMjEtZDgxOWU0NjlhMWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDExMTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNjcwYWViZDA2YjA2N2Q1ZDNlYWE5NTQyMWQ4Nzg1NTVhYmY4NDJkN2Q3NmVmYTcwMTk4YmFiODc1ZTNhY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lkgjGmA4r91YB51C7IkxGi1w1OkoP5EYf2ESru-gAIY)
> 
> * add the `ImageUrl` field in the `hiver. go` files
> 
> ![image](https://private-user-images.githubusercontent.com/69814563/300256838-74556395-db03-4871-b7e7-48dc9d250a01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDA2NDgsIm5iZiI6MTcwNjQ0MDM0OCwicGF0aCI6Ii82OTgxNDU2My8zMDAyNTY4MzgtNzQ1NTYzOTUtZGIwMy00ODcxLWI3ZTctNDhkYzlkMjUwYTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDExMTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NmI1NmNmMTY5Mzk1ZTI0YWQ2ODQyNzA3N2YwNGM5YzY0NWVlOTlmNThkZmM5YTJlMDViNDVhZmY5OWM5MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FR7EYAZK3AlmhwwZzCz_RpY3eB_ytKeW5lO7GzCorLI)

This is correct

**Comment by BamaCharanChhandogi** [comment]
With these changes, should I proceed to raise a pull request (PR)?
