### ISSUE TITLE
[Feature]: Add the pr-title-checker.yml and it's json for keeping tracks of PR. 

### ISSUE THREAD

**Issue by praptisharma28** [Pavel401/Jobs-Scraper#59]
### Describe your improvement idea or feature request

Description
This will :
/Improved Code Organization: Consistent PR titles will enhance code organization and searchability.
/Streamlined Workflow: Integration with CodeQL and a dedicated workflow will promote efficiency and automation.
/Reduced Manual Effort: Automated checks will minimize the need for manual title review, freeing up time for development tasks.

### How would you like to see it implemented?

on github actions

### How can we contact you (optional)

@praptisharma282003@gmail.com

### Would you like to work on this issue?

Yes

### By submitting this issue, I have confirmed that:

- [X] I have starred the repo ⭐

**Comment by praptisharma28** [comment]
Assign me @Pavel401

**Comment by Pavel401** [comment]
@praptisharma28 Test it and attach the demo in the PR.
